name: 'Setup Spring Build'
description: 'Setup tools to build and release Spring Projects'
author: 'Pivotal'
inputs:
  use-wrapper:
    description: 'Prefer using maven/gradle wrapper'
    required: false
  build-mode:
    description: 'Use maven or gradle'
    required: false
  maven-version:
    description: 'The Maven version to make available on the path. Takes a whole
       or semver Maven version, or 3.x syntax (e.g. 3.6 => Maven 3.x)'
    required: true
  maven-file:
    description: 'Path to where the compressed Maven is located. The path could
       be in your source repository or a local path on the agent.'
    required: false
  maven-mirror:
    description: 'Uri to Maven mirror hosting package'
    required: false
    default: 'https://archive.apache.org/dist/maven/maven-3/'
  gradle-version:
    description: 'The Gradle version to make available on the path. Takes a whole
       or semver Gradle version, or 3.x syntax (e.g. 3.6 => Gradle 3.x)'
    required: true
  gradle-file:
    description: 'Path to where the compressed Gradle is located. The path could
       be in your source repository or a local path on the agent.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
