name: 'Setup Spring Build'
description: 'Setup tools to build and release Spring Projects'
author: 'Pivotal'
inputs:
  jfrog-cli-version:
    description: 'The JFrog CLI version to make available on the path'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
